name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
      - run: echo ${{ github.sha }}
      - run: echo ${{ github.ref  }}
  randomly-fail:
    runs-on: ubuntu-latest
    steps:
      - run: echo rand
      - run: '[[ $(($RANDOM%2)) -eq 0 ]]'
  always-fail:
    runs-on: ubuntu-latest
    steps:
      - run: '[[ 1 -eq 0 ]]'
  test:
    runs-on: ubuntu-latest
    needs: check-bats-version
    steps:
      - run: yarn test:ci
